# Generated by Django 3.2.7 on 2021-10-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JugglingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_location', models.CharField(max_length=200)),
                ('pattern', models.CharField(max_length=60)),
                ('juggler', models.CharField(max_length=100)),
                ('comment', models.TextField(null=True)),
                ('catches', models.IntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
