# Generated by Django 3.2.7 on 2021-10-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugglingapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugglingrecord',
            name='file_location',
        ),
        migrations.AddField(
            model_name='jugglingrecord',
            name='audio_file',
            field=models.FileField(default='', upload_to='tmp/'),
            preserve_default=False,
        ),
    ]
